apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../base

resources:
  - notification-cm.yaml
  
patchesStrategicMerge:
  - service-cm.yaml
  - subscription-cm.yaml
  - template-cm.yaml
  - trigger-cm.yaml

patchesJson6902:
  - target:
      kind: Secret
      name: argocd-notifications-secret
      version: v1
    path: patch-slack-secret.yaml